# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
---
include:
  # Corne Choc Pro BT: RIGHT half is the ZMK central.
  # The left half is forced to peripheral even though Keebart defaults it to central.
  - board: corne_choc_pro_left
    snippet: studio-rpc-usb-uart
    shield: nice_view
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n

  # The display is on the right half, so make it central.
  # Battery fetching lets the right half receive the left half battery level.
  # ZMK Studio must run on the central half as well.
  - board: corne_choc_pro_right
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y -DCONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y -DCONFIG_ZMK_STUDIO=y

  - board: corne_choc_pro_left
    shield: settings_reset
    snippet: studio-rpc-usb-uart
  - board: corne_choc_pro_right
    shield: settings_reset
    snippet: studio-rpc-usb-uart

  - board: piantor_pro_bt_left
    snippet: studio-rpc-usb-uart
    shield: nice_view
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: piantor_pro_bt_right
    shield: nice_view
    snippet: studio-rpc-usb-uart

  - board: piantor_pro_bt_left
    shield: settings_reset
    snippet: studio-rpc-usb-uart
  - board: piantor_pro_bt_right
    shield: settings_reset
    snippet: studio-rpc-usb-uart

  - board: sofle_choc_pro_left
    snippet: studio-rpc-usb-uart
    shield: nice_view_disp
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: sofle_choc_pro_right
    shield: nice_view_disp
    snippet: studio-rpc-usb-uart

  - board: sofle_choc_pro_left
    shield: settings_reset
    snippet: studio-rpc-usb-uart
  - board: sofle_choc_pro_right
    shield: settings_reset
    snippet: studio-rpc-usb-uart
